# Generated by Django 3.2.7 on 2022-03-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='account/images/profile')),
                ('image', models.ImageField(upload_to='account/images')),
                ('description', models.TextField(default='', max_length=2000)),
                ('skills1', models.CharField(default='', max_length=50)),
                ('skills2', models.CharField(default='', max_length=50)),
                ('skills3', models.CharField(default='', max_length=50)),
                ('skills4', models.CharField(default='', max_length=50)),
                ('skills5', models.CharField(default='', max_length=50)),
                ('github', models.URLField(default='', max_length=500)),
                ('linkedin', models.URLField(default='', max_length=500)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
