# Generated by Django 3.2.7 on 2022-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220324_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clubs',
            field=models.JSONField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='account',
            name='is_club_member',
            field=models.BooleanField(default=False),
        ),
    ]
