# Generated by Django 3.2.7 on 2022-06-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220611_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='word1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='word2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='word3',
            field=models.CharField(default='', max_length=20),
        ),
    ]
