# Generated by Django 3.2.7 on 2022-06-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220611_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mjskl',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
