# Generated by Django 3.2.9 on 2022-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220612_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='word1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='word2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='word3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
