# Generated by Django 3.2.13 on 2022-08-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220612_2336'),
        ('account', '0008_auto_20220612_1939'),
    ]

    operations = [
    ]
