# Generated by Django 3.2.9 on 2022-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_remove_events_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
