# Generated by Django 3.2.9 on 2022-07-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clubs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
