# Generated by Django 3.2.13 on 2022-08-31 08:16

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField(null=True)),
                ('Banner_image', models.ImageField(default='', upload_to='blog/images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
