# Generated by Django 3.2.13 on 2022-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=60)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(default='', max_length=4)),
                ('USN', models.CharField(default='', max_length=10)),
                ('contact', models.CharField(default='0000000000', max_length=10)),
                ('main_image', models.ImageField(blank=True, upload_to='Almuni/images')),
                ('instagram', models.URLField(blank=True, default='', max_length=1000)),
                ('linkedin', models.URLField(blank=True, default='', max_length=1000)),
                ('mail', models.URLField(blank=True, default='', max_length=500)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
