# Generated by Django 3.2.9 on 2022-07-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almuni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=60)),
                ('branch_and_year', models.CharField(max_length=50)),
                ('main_image', models.ImageField(blank=True, upload_to='Clubs/images')),
                ('instagram', models.URLField(blank=True, default='', max_length=500)),
                ('linkedin', models.URLField(blank=True, default='', max_length=500)),
                ('mail', models.URLField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
