# Generated by Django 3.2.13 on 2022-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almuni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almuni',
            old_name='branch_and_year',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='almuni',
            name='year',
            field=models.CharField(default='', max_length=4),
        ),
    ]
