# Generated by Django 3.2.13 on 2022-09-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almuni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almuni',
            name='USN',
        ),
    ]
