# Generated by Django 3.2.13 on 2022-09-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almuni', '0002_remove_almuni_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='almuni',
            name='USN',
            field=models.CharField(default='', max_length=10),
        ),
    ]
