# Generated by Django 3.2.9 on 2022-07-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image2',
        ),
    ]
